#go<1.20
FROM alpine:3.22
RUN apk add --no-cache go {dependence apk} git \
 && git clone --depth 1 --single-branch --branch {branch} {source} /app_b \
 && cd /app_b/{source} \
 && GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-s -w" -o /app \
 && go clean --cache --modcache --testcache --fuzzcache \ 
 && apk del go {dependence apk} git \
 && rm -rf /app_b /var/cache/apk/* /{dependence build}
# && rm -rf /app_b /var/cache/apk/* /root/go /root/.cache /{dependence build}
