#after shrink
#go=>1.23
FROM alpine:3.22
RUN apk add --no-cache go ca-certificates git \
 && git clone --depth 1 --single-branch --branch master https://github.com/pocketbase/pocketbase  /app_b \
 && GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -C /app_b/examples/base -ldflags "-s -w" -o /app \
 && go clean --cache --modcache --testcache --fuzzcache \ 
 && apk del go git \
 && rm -rf /app_b /var/cache/apk/*
EXPOSE 8080
CMD ["/app", "serve", "--http=0.0.0.0:8080"]
